### ISSUE TITLE
ThresholdLoggingTracer support for DependencyInjection

### ISSUE THREAD

**Issue by mikejmoody** [couchbaselabs/Couchbase.Extensions#75]
Hi

We have been using the DependencyInjection injection extension to simplify our DI code very successfully for some time now and with no issues at all.

However in order to try to pinpoint some weird variances in call times through the SDK we need to add in the ThresholdLoggingTracer to the config on startup. However the DependencyInjection extensions provide no way of accessing the ClientConfiguration object. 

Is there some way to set up the tracer as it stands at the moment, and if not could this be added?

Thanks,
Mike

**Comment by brantburnett** [comment]
@mikejmoody 

At this time, you can only configure the options available in CouchbaseClientDefinition via the DI framework. That option doesn't appear to be available on CouchbaseClientDefinition, only on ClientConfiguration.

That said, the DI system is pretty extensible so you should be able to make it work. Just write a custom version of  ClusterProvider (current code is here https://github.com/couchbaselabs/Couchbase.Extensions/blob/master/src/Couchbase.Extensions.DependencyInjection/Internal/ClusterProvider.cs). I'm spitballing from memory, but it would probably look like this:

cs
```
using System;
using Couchbase.Authentication;
using Couchbase.Configuration.Client;
using Couchbase.Core;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace YourNamespace
{
    internal class ThresholdLoggingClusterProvider : IClusterProvider
    {
        private readonly IOptions<CouchbaseClientDefinition> _options;
        private readonly ILoggerFactory _loggerFactory;
        private ICluster _cluster;
        private bool _disposed = false;

        public ClusterProvider(IOptions<CouchbaseClientDefinition> options, ILoggerFactory loggerFactory)
        {
            _options = options ?? throw new ArgumentNullException(nameof(options));
            _loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
        }

        public virtual ICluster GetCluster()
        {
            if (_disposed)
            {
                throw new ObjectDisposedException(nameof(ClusterProvider));
            }

            if (_cluster != null)
            {
                return _cluster;
            }

            _cluster = CreateCluster(_options.Value);

            return _cluster;
        }

        /// <summary>
        /// Seam for injecting mock
        /// </summary>
        protected virtual ICluster CreateCluster(CouchbaseClientDefinition clientDefinition)
        {
            var configuration = new ClientConfiguration(clientDefinition)
            {
                LoggerFactory = _loggerFactory
            };

            configuration.ThresholdLoggingTracer = new XXX();

            ICluster cluster = new Cluster(configuration);
            if (!string.IsNullOrWhiteSpace(clientDefinition.Username))
            {
                cluster.Authenticate(new PasswordAuthenticator(clientDefinition.Username, clientDefinition.Password));
            }

            return cluster;
        }

        public void Dispose()
        {
            if (!_disposed)
            {
                _disposed = true;

                if (_cluster != null)
                {
                    _cluster.Dispose();
                    _cluster = null;
                }
            }
        }
    }
}
```

Then, you can register DI to use your custom IClusterProvider implementation rather than the default one like so:

cs
```
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddSingleton<IClusterProvider, ThresholdLoggingClusterProvider>()
        .AddCouchbase(...);
}
```

The key is to make sure you register the customer IClusterProvider *before* you call AddCouchbase so that it will take precedence.

**Comment by mikejmoody** [comment]
@brantburnett 

You're a lifesaver. That worked a charm.
